apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.deployment.name }}-config
              key: {{ $key }}
        {{- end }}
        {{- if .Values.secrets }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.jwtSecretName }}
              key: {{ .Values.secrets.jwtSecretKey }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
