appName: appointment-service

deployment:
  name: appointment-service
  labels:
    app: appointment-service
  replicas: 2
  containerName: appointment-app
  containerPort: 7000

image:
  repository: myrepo/appointment-service #!
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  name: appointment-service
  type: ClusterIP
  port: 80              # Cluster içi
  targetPort: 7000      # Container portu
  protocol: TCP

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  CPUTarget: 70
  MemoryTarget: 80

resources: #?
  requests:
    cpu: "150m"
    memory: "128Mi"
  limits:
    cpu: "400m" # hpa varken doğru mu?
    memory: "512Mi"

# Environment variables (?)

# Secrets (?)