appName: gateway-service

deployment:
  name: gateway-service
  labels:
    app: gateway-service
  replicas: 2
  containerName: gateway-app
  containerPort: 8080

image:
  repository: myrepo/gateway-service
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  name: gateway-service
  type: LoadBalancer    # Gateway dışarıya açık olmalı mı? #nginx?
  port: 80              # Cluster içi
  targetPort: 8080      # Container portu
  protocol: TCP

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  CPUTarget: 70
  MemoryTarget: 80

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  APP_ENV: production
  LOG_LEVEL: info
  AUTH_SERVICE_URL: http://auth-service:80
  RATE_LIMIT: "100"
